learning_logs/views.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import current_user, login_required

from learning_log_flask.extentions import db
from .modules import Topic, Entry


ll_bp = Blueprint('ll_bp', __name__, template_folder='templates')

@ll_bp.route('/')
def index():
    """Home page"""
    return render_template('index.html')

@ll_bp.route('/topics')
@login_required
def topics():
    """Show list of all topics"""
    topics = Topic.query.filter_by(owner_id=current_user.id).order_by(Topic.time_added).all()
    return render_template('topics.html', topics=topics)

@ll_bp.route('/topics/<int:topic_id>')
@login_required
def topic(topic_id):
    """Show entries for selected topic"""
    topic = Topic.query.filter_by(id=topic_id, owner_id=current_user.id).first_or_404()
    entries = topic.entries
    context = {'topic': topic, 'entries': entries}
    return render_template('topic.html', **context)

@ll_bp.route('/add_topic', methods=['GET', 'POST'])
@login_required
def add_topic():
    """Add new topic"""
    if request.method == 'POST':
        topic_name = request.form['name']
        topic = Topic(name=topic_name, owner_id=current_user.id)
        db.session.add(topic)
        db.session.commit()
        return redirect(url_for('ll_bp.topics'))
    else:
        return render_template('add_topic.html')

@ll_bp.route('/add_entry/<int:topic_id>', methods=['GET', 'POST'])
@login_required
def add_entry(topic_id):
    """Add new entry to specified topic"""
    topic = Topic.query.filter_by(id=topic_id, owner_id=current_user.id).first_or_404()

    if request.method == 'POST':
        entry_text = request.form['text']
        entry = Entry(text=entry_text, topic_id=topic.id)
        db.session.add(entry)
        db.session.commit()
        return redirect(url_for('ll_bp.topic', **{'topic_id': topic.id}))
    else:
        return render_template('add_entry.html', topic=topic)

@ll_bp.route('/edit_entry/<int:entry_id>', methods=['GET', 'POST'])
@login_required
def edit_entry(entry_id):
    """Edit existed entry"""
    entry = Entry.query.get_or_404(entry_id)
    topic = Topic.query.filter_by(id=entry.topic_id, owner_id=current_user.id).first_or_404()

    if request.method == 'POST':
       edited_text = request.form['text']
       entry.text = edited_text
       db.session.commit()
       return redirect(url_for('ll_bp.topic', **{'topic_id': topic.id}))
    else:
        return render_template('edit_entry.html', entry=entry)  

learning_logs/templates/add_entry.html
{% extends "base.html" %}

{% block page_header %}
    <h2>Add new entry for the topic</h2>
{% endblock page_header %}

{% block content %}
<form method='post' action="{{ url_for('ll_bp.add_entry', **{'topic_id': topic.id}) }}">
    <div class="form-group">
        <textarea class="form-control" name="text" id="text" placeholder="Entry text" rows="3"></textarea>
    </div>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Add</button>
</form>

{% endblock content %}

learning_logs/templates/add_topic.html
{% extends "base.html" %}

{% block page_header %}
    <h2>Add new topic</h2>    
{% endblock page_header %}

{% block content %}

<form class="form-inline mt-2 mt-md-0" method='post' action="{{ url_for('ll_bp.add_topic') }}">
    <input class="form-control mr-sm-2" type="text" name='name' id='name' placeholder="Topic" aria-label="Topic">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Add</button>
</form>

{% endblock content %}

learning_logs/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    {% block styles %}
        {{ bootstrap.load_css() }}
    {% endblock styles %}
    <title>Learning Log</title>
    {% endblock head %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="{{ url_for('ll_bp.index') }}">Learning Log</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('ll_bp.topics') }}">Topics</a>
                </li>
                {% if current_user.is_authenticated %}        
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users_bp.logout') }}" tabindex="-1">Log out</a>
                    </li>
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ current_user.username }}</span>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users_bp.login') }}">Log in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users_bp.register') }}">Register</a>
                    </li>
                {% endif %}        
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

    {% block scripts %}
        {{ bootstrap.load_js() }}
    {% endblock scripts %}
</body>
</html>

learning_logs/templates/edit_entry.html
{% extends "base.html" %}

{% block page_header %}
    <h2>Edit the entry</h2>
{% endblock page_header %}

{% block content %}
    <form method='post' action="{{ url_for('ll_bp.edit_entry', **{'entry_id': entry.id}) }}">
        <div class="form-group">
            <textarea class="form-control" name="text" id="text" placeholder="Entry text" rows="3">{{ entry.text }}</textarea>
        </div>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Submit</button>
    </form>

{% endblock content %}

learning_logs/templates/index.html
{% extends "base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1  class="display-4">Track your learning</h1>

        {% if current_user.is_authenticated %}
        <p class="lead">Whats up {{ current_user.username }}! You're on your Learning Logs. Go to Topics to check out your topics and make new one. 
            Don't forget to add an entry after you've learned something. Keep tracking your progress!
        </p>
        {% else %}  
        <p class="lead">Hey dude! Welcome to the Learning Logs! You can make your own Learning Log here, and keep a list of the topics you're learning about. 
            Whenever you learn something new about a topic, make an entry summarizing what you've learned.
        </p>
        
        <a class="btn btn-lg btn-primary" href="{{ url_for('users_bp.register') }}" role="button">Register &raquo;</a>
        {% endif %} 

    </div>
{% endblock page_header %}

learning_logs/templates/topic.html
{% extends "base.html" %}

{% block page_header %}
    <h2>Topic: {{ topic.name }}</h2>
{% endblock page_header %}

{% block content %}

<a class="btn btn-outline-success my-2 my-sm-0" href="{{ url_for('ll_bp.add_entry', **{'topic_id': topic.id}) }}" role="button">Add entry</a>

{% if entries %}
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Entries</h6>
    {% for entry in entries %}
        <div class="media text-muted pt-3">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#6f42c1"/><text x="50%" y="50%" fill="#6f42c1" dy=".3em">32x32</text></svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">{{ entry.time_added }}</strong>
            {{ entry.text }}
        </p>
        </div>
        
        <small class="d-block text-right mt-3">
        <a href="{{ url_for('ll_bp.edit_entry', **{'entry_id': entry.id}) }}">Edit entry</a>
        </small>
    {% endfor %}    
</div>    
{% else %}    
    <p>This topic does not have any entry yet</p>
{% endif %}              

{% endblock content %}

learning_logs/templates/topics.html
{% extends "base.html" %}

{% block page_header %}
    <h2>Your topics:</h2>
{% endblock page_header %}
    
{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <a href="{{ url_for('ll_bp.topic', **{'topic_id': topic.id}) }}">{{ topic.name }}</a>
            </li>
        {% endfor %}    
    </ul>

    <a class="btn btn-outline-success my-2 my-sm-0" href="{{ url_for('ll_bp.add_topic') }}" role="button">Add new topic</a>
    
{% endblock content %}